// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RabbitMqHeartbeatListener.Data;

#nullable disable

namespace RabbitMqHeartbeatListener.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241018041731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RabbitMqHeartbeatListener.Data.Service", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeatTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.ToTable("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
